config/routes.rb
Rails.application.routes.draw do
  get "/", to: "exhibitions#index", as: "index"
  get "about", to: "exhibitions#about", as: "about"
  get "signup", to: "users#new", as: "signup"
  get "login", to: "sessions#new", as: "login"
  post "login", to: "sessions#create"
  get "logout", to: "sessions#destroy", as: "logout"
  post "like", to: "likes#create_index"

  resources :sessions, only: [:new, :create, :destroy]
  resources :users, only: [:new, :create, :show, :edit, :update]
  resources :comment_likes, only: [:create]
  resources :likes, only: [:create]

  resources :exhibitions do
    resources :comments, except: [:index, :new, :show], shallow: true
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/exhibition.rb
class Exhibition < ApplicationRecord
  belongs_to :user
  has_many :likes
  has_many :comments
  validates :title, :artist, :category, :gallery, :location, :date_end, :user_id, presence: true
  validates :title, uniqueness: true

  def likes_count
    self.likes.count
  end

  def self.most_liked
    Exhibition.all.max_by {|exhibition| exhibition.likes.count}
  end

  def self.most_occurring_location
    locs = Exhibition.all.map {|exhibition| exhibition.location}
    locs.max_by { |i| locs.count(i)}
  end

  def self.exhib_count
    Exhibition.where(location: Exhibition.most_occurring_location).count
  end


  def self.total_average_likes
    all_likes = Exhibition.all.map {|exhibition| exhibition.likes.count}
    average = all_likes.sum / all_likes.size
  end

  def self.filter(*args)
      args = args.first.select {|k, v| v != ""}
      Exhibition.all.where(args)
  end

  def self.locations
    Exhibition.all.map {|loc| loc.location}
  end
  def self.galleries
    Exhibition.all.map {|gal| gal.gallery}
  end
  def self.categories
    Exhibition.all.map {|cat| cat.category}
  end
end

app/controllers/exhibitions_controller.rb
class ExhibitionsController < ApplicationController
    helper_method :most_likes, :most_comment_likes

    def index
        if !params[:exhibition].nil?
            if params[:exhibition].each {|hash| hash}.all? {|k, v| v == ""}
                @exhibitions = Exhibition.all
            else
                @exhibitions = Exhibition.filter(spec_params(:gallery, :category, :location))
                @exhibitions = if @exhibitions.empty?
                  flash[:notice] = "This search has no exhibitions, please try again."
                else
                  @exhibitions
                end
            end
        else
            @exhibitions = Exhibition.all
        end
        @locations = Exhibition.locations.uniq
        @galleries = Exhibition.galleries.uniq
        @categories = Exhibition.categories.uniq
        @selected_loc = params[:exhibition].nil? ? "" : params[:exhibition][:location]
        @selected_cat = params[:exhibition].nil? ? "" : params[:exhibition][:category]
        @selected_gal = params[:exhibition].nil? ? "" : params[:exhibition][:gallery]
        @like = Like.new
    end

    def show
      @exhibition = Exhibition.find(params[:id])
      @comments = @exhibition.comments
      @comment = Comment.new
      @like = Like.new
      @comment_like = CommentLike.new
    end

    def new
      @exhibition = Exhibition.new
    end

    def create
      exhib = Exhibition.create(exhibition_params)
      if exhib.valid?
        redirect_to exhibition_path(exhib)
      else
        flash[:errors] = exhib.errors.full_messages
        render 'new'
      end
    end

    def edit
      @exhibition = Exhibition.find(params[:id])
    end

    def update
      @exhibition = Exhibition.find(params[:id])
      if @exhibition.update(exhibition_params)
          redirect_to @exhibition
      else
          render "edit"
      end
    end

    def destroy
      @exhibition = Exhibition.find(params[:id])
      @exhibition.destroy
      redirect_to exhibitions_path
    end


    private

    def spec_params(*args)
        params.require(:exhibition).permit(args)
    end

    def exhibition_params
        params.require(:exhibition).permit(:title, :artist, :category, :gallery, :location, :date_end, :user_id, :picture)
    end

    def most_likes(array)
        array.sort_by { |exhibition| exhibition.likes.count}.reverse
    end

    def most_comment_likes(array)
        array.sort_by { |comment| comment.comment_likes_count}.reverse
    end
end

app/helpers/exhibitions_helper.rb
module ExhibitionsHelper
end

app/views/exhibitions/_exhib_form.html.erb
<div class="panel panel-default">
  <div class="panel-body">
    <%= form_for @exhibition do |f| %>
        <%= f.label "Exhibition title" %>
        <%= f.text_field :title, class: "form-control" %><br>
        <%= f.label "Artist" %>
        <%= f.text_field :artist, class: "form-control" %><br>
        <%= f.label "Gallery" %>
        <%= f.text_field :gallery, class: "form-control" %><br>
        <%= f.label "Location in London" %>
        <%= f.select :location, options_for_select([["Select One", ""], "Central London", "North London", "South London", "East London", "West London"]), class: "form-inline" %><br>
        <%= f.label "Exhibition end date" %>
        <%= f.date_select :date_end, :order => [:day, :month, :year], class: "form-inline" %><br>
        <%= f.label "Category" %>
        <%= f.select :category, options_for_select([["Select One", ""], "Contemporary", "Modern", "Classical"]), class: "form-inline" %><br>
        <%= f.label :picture %>
        <%= f.filestack_field :picture, 'Upload Your Exhibition photo', class: "form-group" %><br>
        <%= f.hidden_field :user_id, value: current_user.id %>
        <%= f.submit class: "btn btn-primary" %><br>
    <% end %>
  </div>
</div>

app/views/exhibitions/about.html.erb
<div class="title-container">
  <h2>About C.U.Rate</h2>
</div>

  <p>C.U.Rate is an art focused social platform where users can rate exhibitions through comments and likes. Exhibitions are ordered most popular first so it's easy to see what everyone is enjoying. Get your visual recommendations here! Exhibitions curated by popular demand!</p>

  <h2>C.U.Rate stats</h2>
  <div class="right">
    <div class="exhibition">
      <div class="thumbnail">
        <div class="text-center">
          <div class="caption">
            <h4>Current top exhibition:</h4>
            <h4><%= link_to Exhibition.most_liked.title, exhibition_path(Exhibition.most_liked) %></h4>
            <%= filestack_image Exhibition.most_liked.picture, transform: filestack_transform.resize(width: 200, height: 200) %>
          </div>
        </div>
      </div>
    </div>
  </div>
<ul>
  <br>
  <li><h4>The current number of users on C.U.Rate is <%= User.all.count %>.</h4></li>
  <li><h4>The average total number of likes on C.U.Rate is <%= Exhibition.total_average_likes %>!</h4></li>
  <li><h4><%= "The area with the most C.U.Rate listed exhibitions taking place is #{Exhibition.most_occurring_location}, which currently has #{(Exhibition.exhib_count)} listed exhibitions." %></h4></li>
  <li><h4><%= "The most popular exhibition is currently #{Exhibition.most_liked.title} in #{Exhibition.most_liked.location}, with #{Exhibition.most_liked.likes.count} likes!" %></h4></li>
</ul>

app/views/exhibitions/edit.html.erb
<div class="title-container">
  <h1>Edit exhibition</h1>
</div>
  <%= render 'exhib_form' %>

  <%= form_tag exhibition_path(@exhibition), method: "delete" do %>
    <%= submit_tag "Delete exhibition" %>
  <% end %>

app/views/exhibitions/index.html.erb
<div class="title-container">
  <h1>Exhibitions</h1>
    <%= form_tag(index_path, method: "get") do %>
      <%= label_tag "Gallery"%>
      <%= select_tag "exhibition[gallery]", options_for_select(@galleries, @selected_gal), include_blank: true %>
      <%= label_tag "Category"%>
      <%= select_tag "exhibition[category]", options_for_select(@categories, @selected_cat), include_blank: true %>
      <%= label_tag "Location"%>
      <%= select_tag "exhibition[location]", options_for_select(@locations, @selected_loc), include_blank: true %>

    <%= submit_tag("Filter") %>
  <% end %>

</div>

<div class="exhibitions">
  <% if flash[:notice] %>
    <%= flash[:notice] %>
    <% else %>
      <% exhibs = most_likes(@exhibitions) %>
        <% exhibs.each do |exhibition| %>
          <div class="exhibition">
            <div class="thumbnail">
              <div class="text-center">
              <div class="caption">
                <h4><%= link_to exhibition.title, exhibition_path(exhibition) %></h4>
                <div class ="img">
                  <%= filestack_image exhibition.picture, transform: filestack_transform.resize(width: 200, height: 200) %>
                </div><br>
                <% if current_user %>
                  <%= form_for @like, url: "/like", method: 'post' do |f| %>
                    <%= f.hidden_field :exhibition_id, value: exhibition.id %>
                    <%= f.hidden_field :user_id, value: current_user.id %>
                    <%= f.submit "Like #{exhibition.likes_count}"%><br>
                  <% end %>
          <% end %>
              </div>
              </div>
            </div>
          </div>
        <% end %>
      <% end %>
</div>

app/views/exhibitions/new.html.erb
<div class="title-container">
  <h1>Add an exhibition:</h1>
</div>
  <%= render 'exhib_form' %>

app/views/exhibitions/show.html.erb
<div class="center">
  <h2><%= @exhibition.title %>, <%= @exhibition.artist %> </h2>
  <p><%= @exhibition.gallery %>, <%= @exhibition.location %> </p>
  <p>Exhibition ends: <%= localize(@exhibition.date_end) %></p>
  <p><%= @exhibition.category %></p>


  <p>
    <%= filestack_image @exhibition.picture, transform: filestack_transform.resize(width: 300, height: 300) %>
  </p>

  <% if current_user %>
  <% if current_user.id == @exhibition.user_id %>
  <%= link_to("Edit exhibition", edit_exhibition_path(@exhibition)) %>
  <% end %>
  <% end %>

  <% if current_user %>
  <%= form_for @like do |f| %>
      <%= f.hidden_field :exhibition_id, value: @exhibition.id %>
      <%= f.hidden_field :user_id, value: current_user.id %>

      <%= f.submit "Like #{@exhibition.likes_count}"%><br>
  <% end %>
  <% end %>

  <br>
</div>
<% if current_user %>
  <%= render 'comments/comment_form', comment: @comment %>
<% end %>
<br>


<h5>Exhibition comments:</h5><br>
  <% if @comments && !@comments.empty? %>
    <% comms = most_comment_likes(@comments) %>
      <% comms.each do |comment| %>
        <%= comment.content %><br>
        <%= comment.user_comment %>, commented at <%= comment.created_at %><br>

          <% if current_user %>
              <%= form_for @comment_like, url: "/comment_likes", method: 'post' do |f| %>
                <%= f.hidden_field :comment_id, value: comment.id %>
                <%= f.hidden_field :user_id, value: current_user.id %>
                <%= f.submit "Like #{comment.comment_likes_count}"%><br>
              <% end %>
          <% end %>

        <% if current_user %>
          <% if current_user.user_name == comment.user_comment %>
            <%= link_to("Edit comment", edit_comment_path(comment)) %>
          <% end %>
        <% end %>
      <br>
      <br>
    <% end %>
  <% else %>
      <%= "No comments just yet." %>
  <% end %>