config/routes.rb
Rails.application.routes.draw do
  get "/", to: "exhibitions#index", as: "index"
  get "about", to: "exhibitions#about", as: "about"
  get "signup", to: "users#new", as: "signup"
  get "login", to: "sessions#new", as: "login"
  post "login", to: "sessions#create"
  get "logout", to: "sessions#destroy", as: "logout"
  post "like", to: "likes#create_index"

  resources :sessions, only: [:new, :create, :destroy]
  resources :users, only: [:new, :create, :show, :edit, :update]
  resources :comment_likes, only: [:create]
  resources :likes, only: [:create]

  resources :exhibitions do
    resources :comments, except: [:index, :new, :show], shallow: true
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/user.rb
class User < ApplicationRecord
    has_many :likes
    has_many :exhibitions
    has_many :liked_exhibitions, through: :likes, source: :exhibition
    has_many :comment_likes
    has_many :comments, through: :comment_likes
    has_secure_password
    validates :first_name, :last_name, :user_name, :password, presence: true
    validates :user_name, uniqueness: true

    def full_name
        "#{self.first_name} #{self.last_name}"
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    before_action :require_login
    skip_before_action :require_login, only: [:new, :create]

    def show
      @user = User.find(params[:id])
    end

    def new
        @user = User.new
    end

    def create
        user = User.create(user_params)
        if user.valid?
            session[:user_id] = user.id
            redirect_to index_path
        else
            flash[:errors] = user.errors.full_messages
            redirect_to  signup_path
        end
    end

    def show
        @user = User.find(params[:id])
    end

    def edit
        @user = User.find(params[:id])
    end

    def update
        @user = User.find(params[:id])
        if @user.update(user_params)
            flash[:notice] = "Profile successfuly updated"
            redirect_to @user
        else
            flash[:errors] = @user.errors.full_messages
            render "edit"
        end
    end
  

    private

    def require_login
        return head(:forbidden) unless session.include? :user_id
    end

    def user_params
        params.require(:user).permit(:first_name, :last_name, :user_name, :password, :password_confirmation)
    end


end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_new_form.html.erb
<div class="panel panel-default">
  <div class="panel-body">
    <%= form_for @user do |f| %>
        <%= f.label "First name" %>
        <%= f.text_field :first_name, class: "form-control" %>
        <%= f.label "Last name" %>
        <%= f.text_field :last_name, class: "form-control" %>
        <%= f.label "User name" %>
        <%= f.text_field :user_name, class: "form-control" %>
        <%= f.label :password %>
        <%= f.password_field :password, class: "form-control" %>
        <%= f.label :password_confirmation %>
        <%= f.password_field :password_confirmation, class: "form-control" %>

        <%= f.submit "Sign up", class: "btn btn-primary"%>
    <% end %>
  </div>
</div>

app/views/users/edit.html.erb
<h1>Edit user</h1>
<% if flash[:notice] %>
    <%= flash[:notice] %>
<% elsif flash[:errors] %>
    <p><% flash[:errors].each do %></p>
<%end %>
<% end %>
<%= render 'new_form' %>

app/views/users/new.html.erb
<h1>Sign up</h1>
<%= render 'new_form' %>

app/views/users/show.html.erb
<h1><%= @user.full_name %></h1>

<p><%= link_to "Edit Details", edit_user_path %></p>

<%= "Your exhibitions:" %>
<% @user.exhibitions.each do |exhibition| %>
<ul>
<li><%= link_to(exhibition.title, exhibition_path(exhibition)) %></li>
</ul>
<% end %>