config/routes.rb
Rails.application.routes.draw do
  get "/", to: "exhibitions#index", as: "index"
  get "about", to: "exhibitions#about", as: "about"
  get "signup", to: "users#new", as: "signup"
  get "login", to: "sessions#new", as: "login"
  post "login", to: "sessions#create"
  get "logout", to: "sessions#destroy", as: "logout"
  post "like", to: "likes#create_index"

  resources :sessions, only: [:new, :create, :destroy]
  resources :users, only: [:new, :create, :show, :edit, :update]
  resources :comment_likes, only: [:create]
  resources :likes, only: [:create]

  resources :exhibitions do
    resources :comments, except: [:index, :new, :show], shallow: true
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <title>Curate</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= filestack_js_include_tag %>
    <%= filestack_js_init_tag %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <meta name="viewport" content="width=device-width, initial-scale-1">
    <link href="https://fonts.googleapis.com/css?family=Permanent+Marker&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=PT+Sans+Caption&display=swap" rel="stylesheet">
  </head>


  <body class="body">
    <header class="container">
      <nav class="navbar navbar-default">
        <div class="container-fluid">
          <div class="navbar-header">
            <div id="logo">
            <%= link_to("C.U.Rate", exhibitions_path, class: "navbar-brand") %>
            </div>
          </div>

          <ul class="nav navbar-nav navbar-right">
            <% if current_user %>
              <li><%= link_to "Logged in as #{current_user.full_name}" %></li>
              <li><%= link_to "About", about_path %></li>
              <li><%= link_to "Profile", user_path(current_user) %></li>
              <li><%= link_to "Add exhibition", new_exhibition_path %></li>
              <li><%= link_to "Log Out", logout_path %></li>
            <% else %>
              <li><%= link_to "About", about_path %></li>
              <li><%= link_to "Sign Up", signup_path %></li>
              <li><%= link_to "Log In", login_path %></li>
            <% end %>
          </ul>
        </div>
      </nav>
    </header>

    <section class="container">
      <div id="flash">
        <% if flash[:errors] %>
          <% flash[:errors].each do |error| %>
            <div class="error"><%= error %></div>
          <% end %>
        <% end %>
      </div>
      <%= yield %>
    </section>
  </body>
  <footer>
    <div class="footer">
      <h8>C.U.Rate, created by Le and Louise</h8>
    </div>
  </footer>
</html>